# Generated by Django 2.2.6 on 2019-10-26 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='ModuleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ppm', models.IntegerField(null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='modules.Module')),
            ],
            options={
                'db_table': 'module_data',
            },
        ),
    ]
