# Generated by Django 2.2.6 on 2019-10-26 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20191026_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledata',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_data', to='modules.Module'),
        ),
    ]
