# Generated by Django 2.2.6 on 2019-11-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20191026_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduledata',
            old_name='pressure',
            new_name='velocity',
        ),
    ]
