# Generated by Django 2.2.6 on 2019-11-18 19:02

from django.db import migrations, models
import modules.enum


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20191113_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.CharField(choices=[(modules.enum.ModuleStatusSet('ONLINE'), 'ONLINE'), (modules.enum.ModuleStatusSet('OFFLINE'), 'OFFLINE'), (modules.enum.ModuleStatusSet('UNKNOWN'), 'UNKNOWN'), (modules.enum.ModuleStatusSet('FIRERISK'), 'FIRERISK')], default='UNKNOWN', max_length=255),
        ),
    ]
