# Generated by Django 2.2.6 on 2019-11-25 17:58

from django.db import migrations, models
import modules.enum


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_module_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledata',
            name='signal_strength',
            field=models.IntegerField(default=-113, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.CharField(choices=[(modules.enum.ModuleStatusSet('ONLINE'), 'ONLINE'), (modules.enum.ModuleStatusSet('OFFLINE'), 'OFFLINE'), (modules.enum.ModuleStatusSet('UNKNOWN'), 'UNKNOWN'), (modules.enum.ModuleStatusSet('FIRERISK'), 'FIRERISK'), (modules.enum.ModuleStatusSet('IN_MOTION'), 'IN_MOTION')], default='UNKNOWN', max_length=255),
        ),
    ]
